# train.py
import yaml
from datasets import Dataset
from trl import GRPOTrainer, GRPOConfig
from env import RLEnvironment

def load_config(path="config.yaml"):
    with open(path, "r") as f:
        return yaml.safe_load(f)

def main():
    # 1. Load configuration
    config = load_config()
    
    # 2. Initialize the RL environment (Connecting train.py to env.py)
    env = RLEnvironment(config)

    # 3. Create the Reward Function Wrapper for GRPOTrainer
    # GRPOTrainer passes batches of raw text 'completions' generated by the LLM
    def env_reward_function(completions, **kwargs):
        prompts = kwargs.get("prompts", [""] * len(completions))
        rewards = []
        
        for prompt, completion in zip(prompts, completions):
            # Reset the environment for each prompt in the batch
            env.reset(prompt)
            
            # TODO: Add logic to parse textual 'completion' into structured 'action' dict
            # Example: parsing XML tags or JSON blocks out of the text
            mock_action = {"tool": "none", "input": completion}
            
            # Step the environment
            obs, reward, done, info = env.step(mock_action)
            
            # Make sure we get a final reward if max_steps isn't reached
            if not done:
                reward = env.get_reward()
                
            rewards.append(reward)
            
        return rewards

    # 4. Configure GRPO
    training_args = GRPOConfig(
        output_dir=config["output_dir"],
        learning_rate=float(config["learning_rate"]),
        num_train_epochs=config["num_train_epochs"],
        per_device_train_batch_size=config["per_device_train_batch_size"],
        gradient_accumulation_steps=config["gradient_accumulation_steps"],
        logging_steps=config["logging_steps"],
        bf16=config.get("bf16", False),
        fp16=config.get("fp16", False),
        use_vllm=config.get("use_vllm", False),
        # Add this line to match your batch size
        num_generations=config.get("num_generations", 2) 
    )


    # 5. Load a Dummy Dataset (GRPO requires a dataset with a 'prompt' column)
    # Replace this with your actual tool/reasoning dataset
    dummy_data = {
        "prompt": [
            "Solve this math problem: 2+2", 
            "Search the web for the latest news."
        ]
    }
    dataset = Dataset.from_dict(dummy_data)

    # 6. Initialize and start the Trainer
    trainer = GRPOTrainer(
        model=config["model_name"],
        reward_funcs=[env_reward_function], # Passing our wrapper connected to env.py
        args=training_args,
        train_dataset=dataset,
    )
    
    print("Trainer connected to environment successfully. Ready to start training!")
    # trainer.train()

if __name__ == "__main__":
    main()
